export enum MATH_ALLOCATOR {
    PERSISTENT_MATRIX = 'MATH_PERSISTENT_MATRIX',
    PERSISTENT_MATRIX_CACHE = 'MATH_PERSISTENT_MATRIX_CACHE',
    PERSISTENT_VECTOR = 'MATH_PERSISTENT_VECTOR',
    PERSISTENT_QUATERNION = 'MATH_PERSISTENT_QUATERNION',
    PERSISTENT_QUATERNION_CACHE = 'MATH_PERSISTENT_QUATERNION_CACHE',
}
